require 'fileutils'
require 'rexml/document'

module Xcodeproj

	# Provides support for generating, reading and serializing Xcode Workspace
	# documents.
	#
	class Workspace

		# Generic tree-link container mixin. 
		# 
		module Container

			attr_reader :contents

			# Adds a object to the list of the of contents of this Container.
			#
			# @param  [Object] item
			#         The object to add.
			#
			# @return [void]
			#
			def <<(item)
				@contents << item 
			end

			def traverse(node = self, &block)
				yield node
				node.contents.each { |child| traverse(child, &block) } if node.is_a? Container 
			end

		end

		# Abstract base class that defines types of items that can be contained
		# within a Workspace.
		# 
		class WorkspaceItem

			module LocationType
				ABSOLUTE_PATH             = "absolute"
				RELATIVE_TO_GROUP         = "group"
				RELATIVE_TO_WORKSPACE     = "container"
				RELATIVE_TO_DEVELOPER_DIR = "developer"
			end

			LOCATION_TYPES = 
				[LocationType::ABSOLUTE_PATH, 
				LocationType::RELATIVE_TO_GROUP,
				LocationType::RELATIVE_TO_WORKSPACE, 
				LocationType::RELATIVE_TO_DEVELOPER_DIR]

			attr_reader :location_type

			def location_type=(value)
				raise "[Xcodeproj] Invalid location type '#{value}'." unless LOCATION_TYPES.include? value
				@location_type = value
			end

			attr_accessor :path

			# @return [String] the ISA of the class.
			#
			def self.isa
				@isa ||= name.split('::').last
			end

			# @return [String] the object's class name.
			#
			attr_reader :isa

			def initialize()
				@isa = self.class.isa
			end

			# @return [REXML::Node] the XML representation of the WorkspaceItem
			# 
			def to_xml
				raise "[Xcodeproj] Must be implemented by subclasses."
			end
		end

		# Represents a 'FileRef' in the Workspace. This is most commonly used to
		# reference xcodeproj files, but is it not limited to them.
		# 
		class FileRef < WorkspaceItem

			def initialize(path=nil)
				@isa = self.class.isa
				@path = path
				@location_type = LocationType::RELATIVE_TO_GROUP # this is the default for FileRefs
			end

			def to_xml
				REXML::Element.new("FileRef").tap do |el|
					el.attributes["location"] = "#{@location_type}:#{path}"
				end
			end

			include Comparable

			def <=>(other_fileref)
				if self.path < other_fileref.path
					-1
				elsif self.path > other_fileref.path
					1
				else
					0
				end
			end

		end

		# Represents a 'Group' in the Workspace. Like Groups in Xcode projects,
		# Groups in Workspaces exist only within the context of the Workspace,
		# and do not map to any on-disk folders. They are for organizational
		# purposes only.
		#
		class Group < WorkspaceItem

			# Group objects are Containers.
			# 
			include Container

			attr_accessor :name

			def initialize(name=nil, path=nil)
				@isa = self.class.isa
				@contents = []
				@name = name
				@path = path
				@location_type = LocationType::RELATIVE_TO_WORKSPACE # this is the default for Groups
			end

			def to_xml
				REXML::Element.new("Group").tap do |el|
					el.attributes["location"] = "#{@location_type}:#{path}"
					el.attributes["name"] = @name
					@contents.each { |item| el << item.to_xml }
				end
			end

		end

		# Workspace objects are Containers.
		# 
		include Container

		# @return [Array<String>] the paths of the projects contained in the
		#   workspace.
		#
		def projpaths
			projpaths = []
			traverse do |item| 
				if item.is_a? FileRef and item.path.end_with? 'xcodeproj'
					projpaths << item.path
				end
			end
			projpaths
		end

		def initialize
			@contents = []
		end

		# @param  [String] projpaths @see projpaths
		#
		def initialize(*contents)
			@contents = []

			contents.each do |item|
				if item.is_a? WorkspaceItem
					@contents << item
				elsif item.is_a? String
					@contents << FileRef.new(item)
				end
			end
		end

		# Returns a workspace generated by reading the contents of the given path.
		#
		# @param  [String] path
		#         the path of the `xcworkspace` file.
		#
		# @return [Workspace] the generated workspace.
		#
		def self.new_from_xcworkspace(path)
			begin
				from_s(File.read(File.join(path, 'contents.xcworkspacedata')))
			rescue Errno::ENOENT
				new
			end
		end

		# Returns a workspace generated by reading the contents of the given
		# XML representation.
		#
		# @param [String] xml
		#   the XML representation of the workspace.
		#
		# @return [Workspace] the generated workspace.
		#
		def self.from_s(xml)
			document = REXML::Document.new(xml)
			projpaths = document.get_elements("/Workspace/FileRef").map do |node|
				node.attribute("location").to_s.sub(/^group:/, '')
			end
			new(*projpaths)
		end

		# Adds a new item to the contents of the workspace.
		#
		# @param  [String | WorkspaceItem] item 
		# 	If a String is inserted, it will automatically be converted to a
		# 	FileRef. WorkspaceItems are inserted, as-is. Any other type of object
		# 	is not allowed.
		#
		# @return [void]
		#
		def <<(item)
			if item.is_a? String
				super << FileRef.new(item)
			elsif item.is_a? WorkspaceItem
				super << item
			else
				raise "[Xcodeproj] Attempt to insert unsupported object type in Workspace."
			end
		end

		# Checks if the workspace contains the project with the given path.
		#
		# @param  [String] projpath
		#         The path of the project to add.
		#
		# @return [Boolean] whether the project is contained in the workspace.
		#
		def include?(projpath)
			target = FileRef.new(projpath)
			self.traverse { |item| return true if item == target }
			false
		end

		# The template to generate a workspace XML representation.
		#
		TEMPLATE = %q[<?xml version="1.0" encoding="UTF-8"?><Workspace version="1.0"></Workspace>]

		# @return [String] the XML representation of the workspace.
		#
		def to_s
			REXML::Document.new(TEMPLATE).tap do |document|
				document.context[:attribute_quote] = :quote # use double quotes
				@contents.each do |item|
					document.root << item.to_xml
				end
			end.to_s
		end

		# Saves the workspace at the given `xcworkspace` path.
		#
		# @param  [String] path
		#         the path where to save the project.
		#
		# @return [void]
		#
		def save_as(path)
			FileUtils.mkdir_p(path)
			File.open(File.join(path, 'contents.xcworkspacedata'), 'w') do |out|
				out << to_s
			end
		end

	end
end
